### ISSUE TITLE
Issue with upload on v1.2

### ISSUE THREAD

**Issue by MakerMatrix** [Photonsters/PhotonController#5]
I'm having disconnects when trying to upload a file, on the latest release.  It seems like maybe 2s timeout is too short for the actual upload.  Chitubox is able to upload this same photon file that is repeatedly failing with PNC 1.2.

Out of curiosity, did this parameter change vs. the previous release?  This did not happen with previous versions of this tool.

**Comment by lagnajeet** [comment]
Thanks for the comment. 

Just to make sure, you are talking about this release , right
https://github.com/Photonsters/Universal-Photon-Network-Controller/releases/tag/0.2

I have not changed the timeout in the new version. I just tried uploading a 20mb file and it worked fine for me. I will make the timeout as a setting in the next version. That way the use can set the timeout that suites them.

Please post issue under https://github.com/Photonsters/Universal-Photon-Network-Controller . It will make it easy to keep track of the issues.

**Comment by MakerMatrix** [comment]
Yes, the link posted in the Photonsters FB messenger.  Didn't realize there was another project called "Universal".  Is that where activity is moving to?

Yeah I can't really explain the timeout issue then, if you didn't change it.  I went back to the 0.1 alpha version and it worked fine.  Could be coincidence and some intermittent network issue on my end.  I'll post in the new project if I learn more.

In principle I'd like to be able to build this for myself and hack on it, possibly contribute if I come up with anything useful.  In practice I've done little to no dev work on Windows.  Could you help me get my environmet setup?  What do I need?  What compiler and what toolkit(s) do you use for this?

**Comment by lagnajeet** [comment]
i opened an issue in the universal  controller project page. Here is the link

https://github.com/Photonsters/Universal-Photon-Network-Controller/issues/2

Let me know if it works out for you or not.
